#!/usr/bin/env node
// bench/fixtures/generate.mjs — seeded, idempotent generator for the three
// vendored fixture repos (ADR-0001 §3.3), their claims.json files (exactly
// 100 claims each), and bench/mutations/mutations.json (45 seeded mutations,
// seed 42, across 4 fault classes — ADR §3.2.6 / sub-claim C4).
//
// Re-running this script always produces byte-identical output (no
// timestamps, all randomness from a Park–Miller LCG). The generated files
// are committed; this script exists so the 100-claim workloads are
// reproducible and auditable, never hand-edited.
//
// Usage: node bench/fixtures/generate.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { makeRng, sha256Bytes, harnessHash, LCG_M, LCG_A, rmrf, writeFileEnsured } from '../lib/util.mjs';

const FIXTURES_DIR = path.dirname(fileURLToPath(import.meta.url));
const BENCH_DIR = path.dirname(FIXTURES_DIR);
const GEN_SEED = 1337; // fixture content seed
const MUTATION_SEED = 42; // ADR §3.3: mutation suite seed = 42

const WORDS = [
  'ledger', 'witness', 'anchor', 'quorum', 'beacon', 'cipher', 'tally', 'probe',
  'vault', 'relay', 'shard', 'merkle', 'digest', 'oracle', 'sentry', 'gauge',
  'prism', 'lattice', 'cursor', 'mantle', 'socket', 'kernel', 'pivot', 'strata',
];

function slug(rng) {
  return `${rng.pick(WORDS)}-${rng.pick(WORDS)}-${String(rng.int(900) + 100)}`;
}

// CLAIM-ALLOCATION RULE (makes mutation expectations structurally correct):
// marker-host files carry ONLY marker claims; file-hash claims cover only
// non-host files. A pure file-hash claim has no marker, so any edit to its
// file is a regression (ADR §5.6) — "edit with marker intact → drift" is only
// a valid expectation on files whose claims are all marker claims.

// ---------------------------------------------------------------------------
// repo-a-npm-lib — small TypeScript-ish library, ~35 files, deterministic
// dist/ (build.mjs byte-copies src/*.ts → dist/*.js, so outputs are stable).
// Claims: 20 file-hash (dist + meta) + 80 marker (src hosts) = 100.
// ---------------------------------------------------------------------------
function genRepoA(rng) {
  const files = {};
  const markers = []; // {file, marker, desc}
  const srcFiles = [];

  for (let i = 1; i <= 15; i++) {
    const name = `src/module${String(i).padStart(2, '0')}.ts`;
    srcFiles.push(name);
    const markerCount = i <= 5 ? 6 : 5; // 5*6 + 10*5 = 80
    const lines = [
      `// ${name} — fixture module (generated, deterministic)`,
      `export interface Record${i} { id: string; weight: number; }`,
      '',
    ];
    for (let f = 1; f <= 4; f++) {
      lines.push(
        `export function op${i}_${f}(x: number): number {`,
        `  return x * ${rng.int(97) + 2} + ${rng.int(43)};`,
        `}`,
        '',
      );
    }
    for (let m = 1; m <= markerCount; m++) {
      const id = `fix-a-${String(i).padStart(2, '0')}${m}`;
      const marker = `PROOFKIT:${id} ${slug(rng)}`;
      markers.push({ file: name, marker, desc: `fix ${id} present in ${name}` });
      lines.push(`// ${marker}`);
    }
    lines.push('');
    files[name] = lines.join('\n');
  }

  files['build.mjs'] = [
    '#!/usr/bin/env node',
    "// Trivial deterministic 'build': byte-copies src/*.ts to dist/*.js so",
    '// build outputs are byte-stable across machines (bench fixture only).',
    "import fs from 'node:fs';",
    "import path from 'node:path';",
    "const src = 'src';",
    "const dist = 'dist';",
    'fs.mkdirSync(dist, { recursive: true });',
    'for (const f of fs.readdirSync(src).sort()) {',
    "  if (!f.endsWith('.ts')) continue;",
    "  fs.copyFileSync(path.join(src, f), path.join(dist, f.replace(/\\.ts$/, '.js')));",
    '}',
    '',
  ].join('\n');

  files['package.json'] = JSON.stringify(
    {
      name: 'repo-a-npm-lib',
      version: '0.1.0',
      private: true,
      type: 'module',
      scripts: { build: 'node build.mjs' },
    },
    null,
    2,
  ) + '\n';

  files['tsconfig.json'] = JSON.stringify(
    { compilerOptions: { target: 'ES2022', module: 'NodeNext', strict: true, outDir: 'dist' }, include: ['src'] },
    null,
    2,
  ) + '\n';

  files['README.md'] = '# repo-a-npm-lib\n\nBench fixture: small TS library with a deterministic dist/.\nGenerated by bench/fixtures/generate.mjs — do not hand-edit.\n';
  files['LICENSE'] = 'MIT (bench fixture — generated)\n';

  // Prebuilt dist/ — committed output of build.mjs (byte-identical to src).
  for (const s of srcFiles) {
    files[s.replace(/^src\//, 'dist/').replace(/\.ts$/, '.js')] = files[s];
  }

  // Claims: file-hash on non-host files only (20), markers (80). Total 100.
  const hostFiles = new Set(srcFiles);
  const claims = [];
  let n = 0;
  for (const file of Object.keys(files).sort()) {
    if (hostFiles.has(file)) continue; // marker hosts carry only marker claims
    n += 1;
    claims.push({
      id: `A-FH-${String(n).padStart(3, '0')}`,
      type: 'file-hash',
      desc: `byte-stable: ${file}`,
      file,
      sha256: sha256Bytes(Buffer.from(files[file])),
    });
  }
  markers.forEach((m, i) => {
    claims.push({
      id: `A-MK-${String(i + 1).padStart(3, '0')}`,
      type: 'marker',
      desc: m.desc,
      file: m.file,
      marker: m.marker,
    });
  });
  return { files, claims };
}

// ---------------------------------------------------------------------------
// repo-b-python-tool — Python CLI, 20 files, with a deterministic-output
// harness script (inline Park–Miller LCG reading PROOFKIT_SEED — NOT the
// `random` module). Claims: 5 file-hash + 2 harness + 93 marker = 100.
// ---------------------------------------------------------------------------
function lcgFloats(seed, count) {
  // Exact JS twin of tools/deterministic.py: integer LCG then exact-integer
  // division → identical IEEE-754 doubles in JS and Python.
  let state = (Math.trunc(seed) % (LCG_M - 1)) + 1;
  if (state <= 0) state += LCG_M - 1;
  const out = [];
  for (let i = 0; i < count; i++) {
    state = (state * LCG_A) % LCG_M;
    out.push(state / LCG_M);
  }
  return out;
}

function genRepoB(rng) {
  const files = {};
  const markers = [];

  files['tools/deterministic.py'] = [
    '#!/usr/bin/env python3',
    '"""Deterministic-output harness for the ProofKit bench (ADR D9 pattern).',
    '',
    'Inline Park-Miller LCG (NOT the random module) seeded from PROOFKIT_SEED;',
    'prints 16 floats. Integer state stays < 2^31 so state/M is an exact',
    'IEEE-754 double, byte-identical across CPython versions and platforms.',
    '"""',
    'import os',
    '',
    'M = 2147483647',
    'A = 48271',
    '',
    '',
    'def main() -> None:',
    '    seed = int(os.environ.get("PROOFKIT_SEED", "42"))',
    '    state = (seed % (M - 1)) + 1',
    '    if state <= 0:',
    '        state += M - 1',
    '    for _ in range(16):',
    '        state = (state * A) % M',
    '        print(f"{state / M:.17g}")',
    '',
    '',
    'if __name__ == "__main__":',
    '    main()',
    '',
  ].join('\n');

  const modFiles = [];
  for (let i = 1; i <= 14; i++) {
    const name = `pktool/mod${String(i).padStart(2, '0')}.py`;
    modFiles.push(name);
    const lines = [
      `"""${name} — fixture module (generated, deterministic)."""`,
      '',
      '',
      `def transform_${i}(value: int) -> int:`,
      `    return value * ${rng.int(89) + 2} + ${rng.int(31)}`,
      '',
    ];
    files[name] = lines.join('\n');
  }

  files['pktool/cli.py'] = [
    '"""pktool CLI entrypoint (bench fixture)."""',
    'import sys',
    '',
    '',
    'def main() -> int:',
    '    print("pktool", " ".join(sys.argv[1:]))',
    '    return 0',
    '',
    '',
    'if __name__ == "__main__":',
    '    raise SystemExit(main())',
    '',
  ].join('\n');

  files['README.md'] = '# repo-b-python-tool\n\nBench fixture: Python CLI with a deterministic-output harness.\nGenerated by bench/fixtures/generate.mjs — do not hand-edit.\n';
  files['pyproject.toml'] = '[project]\nname = "repo-b-python-tool"\nversion = "0.1.0"\n';
  files['requirements.txt'] = '# no dependencies (bench fixture)\n';
  files['LICENSE'] = 'MIT (bench fixture — generated)\n';

  // 93 markers across cli.py + 14 modules (15 files): 3 files x 7 + 12 x 6 = 93.
  const markerHosts = ['pktool/cli.py', ...modFiles];
  markerHosts.forEach((file, idx) => {
    const count = idx < 3 ? 7 : 6;
    const extra = [];
    for (let m = 1; m <= count; m++) {
      const id = `fix-b-${String(idx + 1).padStart(2, '0')}${m}`;
      const marker = `PROOFKIT:${id} ${slug(rng)}`;
      markers.push({ file, marker, desc: `fix ${id} present in ${file}` });
      extra.push(`# ${marker}`);
    }
    files[file] = files[file] + extra.join('\n') + '\n';
  });

  const hostFiles = new Set(markerHosts);
  const claims = [];
  let n = 0;
  for (const file of Object.keys(files).sort()) {
    if (hostFiles.has(file)) continue; // marker hosts carry only marker claims
    n += 1;
    claims.push({
      id: `B-FH-${String(n).padStart(3, '0')}`,
      type: 'file-hash',
      desc: `byte-stable: ${file}`,
      file,
      sha256: sha256Bytes(Buffer.from(files[file])),
    });
  }
  // Two harness claims (seeds 42 and 7), expected hashes computed by the JS
  // twin of the LCG — ADR D9: quantize 6 decimals → pack LE f64 → sha256.
  for (const [k, seed] of [[1, 42], [2, 7]]) {
    claims.push({
      id: `B-HN-${String(k).padStart(3, '0')}`,
      type: 'harness',
      desc: `deterministic LCG output stable (seed ${seed})`,
      harness: `lcg-seed-${seed}`,
      file: 'tools/deterministic.py',
      cmd: 'python3 tools/deterministic.py',
      seed,
      quantizeDecimals: 6,
      expectedSha256: harnessHash(lcgFloats(seed, 16), 6),
      tolerance: { rtol: 1e-4, atol: 1e-6 },
    });
  }
  markers.forEach((m, i) => {
    claims.push({
      id: `B-MK-${String(i + 1).padStart(3, '0')}`,
      type: 'marker',
      desc: m.desc,
      file: m.file,
      marker: m.marker,
    });
  });
  return { files, claims };
}

// ---------------------------------------------------------------------------
// repo-c-docs-site — 15 Markdown/config files.
// Claims: 5 file-hash + 95 marker = 100.
// ---------------------------------------------------------------------------
function genRepoC(rng) {
  const files = {};
  const markers = [];

  const pages = [];
  for (let i = 1; i <= 10; i++) {
    const name = `docs/page${String(i).padStart(2, '0')}.md`;
    pages.push(name);
    files[name] = [
      `# Page ${i}`,
      '',
      `This is fixture documentation page ${i} (${slug(rng)}).`,
      '',
      `- topic: ${rng.pick(WORDS)}`,
      `- detail: ${rng.pick(WORDS)} ${rng.int(1000)}`,
      '',
    ].join('\n');
  }
  files['index.md'] = '# repo-c-docs-site\n\nBench fixture docs site.\nGenerated by bench/fixtures/generate.mjs — do not hand-edit.\n';
  files['mkdocs.yml'] = 'site_name: repo-c-docs-site\nnav:\n  - Home: index.md\n';
  files['.github/workflows/ci.yml'] = [
    'name: docs-ci',
    'on: [push]',
    'jobs:',
    '  lint:',
    '    runs-on: ubuntu-latest',
    '    steps:',
    '      - uses: actions/checkout@v4',
    '      - run: echo lint-ok',
    '',
  ].join('\n');
  files['README.md'] = '# repo-c-docs-site (bench fixture)\n';
  files['LICENSE'] = 'MIT (bench fixture — generated)\n';

  // 95 markers across 10 host files: index.md + pages 1-8 + ci.yml.
  // 5 files x 10 + 5 files x 9 = 95. Markers are HTML/yaml-comment lines.
  // (page09, page10, mkdocs.yml, README, LICENSE stay marker-free → file-hash.)
  const hosts = ['index.md', ...pages.slice(0, 8), '.github/workflows/ci.yml'];
  hosts.forEach((file, idx) => {
    const count = idx < 5 ? 10 : 9;
    const isYml = file.endsWith('.yml');
    const extra = [];
    for (let m = 1; m <= count; m++) {
      const id = `fix-c-${String(idx + 1).padStart(2, '0')}${m}`;
      const marker = `PROOFKIT:${id} ${slug(rng)}`;
      markers.push({ file, marker, desc: `fix ${id} present in ${file}` });
      extra.push(isYml ? `# ${marker}` : `<!-- ${marker} -->`);
    }
    files[file] = files[file] + extra.join('\n') + '\n';
  });

  const hostFiles = new Set(hosts);
  const claims = [];
  let n = 0;
  for (const file of Object.keys(files).sort()) {
    if (hostFiles.has(file)) continue; // marker hosts carry only marker claims
    n += 1;
    claims.push({
      id: `C-FH-${String(n).padStart(3, '0')}`,
      type: 'file-hash',
      desc: `byte-stable: ${file}`,
      file,
      sha256: sha256Bytes(Buffer.from(files[file])),
    });
  }
  markers.forEach((m, i) => {
    claims.push({
      id: `C-MK-${String(i + 1).padStart(3, '0')}`,
      type: 'marker',
      desc: m.desc,
      file: m.file,
      marker: m.marker,
    });
  });
  return { files, claims };
}

// ---------------------------------------------------------------------------
// Mutations — seed 42, 45 entries (>= 40 required), 4 classes (ADR C4):
//  (a) manifest-byte  : single-byte mutation of the sealed trust artifact   → fail
//  (b) marker-removal : remove a claimed marker line                         → fail
//  (c) edit-marker-intact: edit a claimed file, marker preserved             → drift
//  (d) file-deletion  : delete a claimed file                                → missing
// ---------------------------------------------------------------------------
function genMutations(fixtureClaims) {
  const rng = makeRng(MUTATION_SEED);
  const mutations = [];
  let seq = 0;
  const push = (m) => mutations.push({ id: `M-${String(++seq).padStart(3, '0')}`, ...m });

  const manifestTargets = [
    'manifest:integrity.signature',
    'manifest:claims[].sha256',
    'manifest:manifest.summary.verified',
    'manifest:integrity.manifestHash',
  ];

  for (const [fixture, claims] of Object.entries(fixtureClaims)) {
    const markerClaims = claims.filter((c) => c.type === 'marker');
    // Deletion targets must be pure file-hash claims: deleting a file that a
    // harness claim references would regress the harness (→ fail), not just
    // go missing — keep the expected classification unambiguous.
    const harnessFiles = new Set(claims.filter((c) => c.type === 'harness').map((c) => c.file));
    const fileClaims = claims.filter((c) => c.type === 'file-hash' && !harnessFiles.has(c.file));

    // (a) 4 single-byte manifest mutations per fixture.
    for (const target of manifestTargets) {
      push({
        class: 'manifest-byte',
        fixture,
        target,
        operation: `flip-hex-nibble@${rng.int(32)}`,
        expectedDetection: 'fail',
      });
    }

    // Seeded, collision-free claim picks.
    const pickDistinct = (arr, count, used) => {
      const out = [];
      while (out.length < count) {
        const c = rng.pick(arr);
        if (used.has(c.id)) continue;
        used.add(c.id);
        out.push(c);
      }
      return out;
    };
    const usedMarkers = new Set();

    // (b) 4 marker removals per fixture → regressed → fail.
    for (const c of pickDistinct(markerClaims, 4, usedMarkers)) {
      push({
        class: 'marker-removal',
        fixture,
        target: `${c.file}#${c.id}`,
        operation: 'remove-marker-line',
        expectedDetection: 'fail',
      });
    }

    // (c) 4 edits with marker intact per fixture → MUST classify drift.
    for (const c of pickDistinct(markerClaims, 4, usedMarkers)) {
      push({
        class: 'edit-marker-intact',
        fixture,
        target: `${c.file}#${c.id}`,
        operation: 'append-benign-line',
        expectedDetection: 'drift',
      });
    }

    // (d) 3 file deletions per fixture → missing.
    const usedFiles = new Set();
    let attempts = 0;
    while (usedFiles.size < 3 && attempts < 1000) {
      attempts += 1;
      const c = rng.pick(fileClaims);
      if (usedFiles.has(c.file)) continue;
      usedFiles.add(c.file);
      push({
        class: 'file-deletion',
        fixture,
        target: `${c.file}#${c.id}`,
        operation: 'delete-file',
        expectedDetection: 'missing',
      });
    }
  }
  return mutations;
}

// ---------------------------------------------------------------------------
// Main — idempotent: wipes and regenerates the three fixture dirs and
// mutations.json with byte-identical content.
// ---------------------------------------------------------------------------
function writeFixture(name, { files, claims }) {
  const dir = path.join(FIXTURES_DIR, name);
  rmrf(dir);
  for (const [rel, content] of Object.entries(files)) {
    writeFileEnsured(path.join(dir, rel), content);
  }
  if (claims.length !== 100) {
    throw new Error(`${name}: expected exactly 100 claims, got ${claims.length}`);
  }
  writeFileEnsured(
    path.join(dir, 'claims.json'),
    JSON.stringify({ schema: 'proofkit-bench-claims/v1', fixture: name, generatorSeed: GEN_SEED, claims }, null, 2) + '\n',
  );
  return claims;
}

function main() {
  const rng = makeRng(GEN_SEED);
  const fixtureClaims = {
    'repo-a-npm-lib': writeFixture('repo-a-npm-lib', genRepoA(rng)),
    'repo-b-python-tool': writeFixture('repo-b-python-tool', genRepoB(rng)),
    'repo-c-docs-site': writeFixture('repo-c-docs-site', genRepoC(rng)),
  };

  const mutations = genMutations(fixtureClaims);
  writeFileEnsured(
    path.join(BENCH_DIR, 'mutations', 'mutations.json'),
    JSON.stringify({ schema: 'proofkit-bench-mutations/v1', seed: MUTATION_SEED, count: mutations.length, mutations }, null, 2) + '\n',
  );

  for (const [name, claims] of Object.entries(fixtureClaims)) {
    const byType = {};
    for (const c of claims) byType[c.type] = (byType[c.type] || 0) + 1;
    console.log(`${name}: ${claims.length} claims`, byType);
  }
  console.log(`mutations: ${mutations.length} (seed ${MUTATION_SEED})`);
}

main();
